# Generated by Django 3.2.7 on 2021-10-02 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amazon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('color', models.CharField(max_length=20)),
                ('ram', models.IntegerField()),
                ('rom', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Compare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('color', models.CharField(max_length=20)),
                ('ram', models.IntegerField()),
                ('rom', models.IntegerField()),
                ('amazon_price', models.IntegerField()),
                ('flipcart_price', models.IntegerField()),
                ('diff', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Flipcart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('color', models.CharField(max_length=20)),
                ('ram', models.IntegerField()),
                ('rom', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
